version: "2.0"
services:
  unicorndashboard:
    build:
      context: "./multi_dashboard/"
    networks:
      - frontend
    privileged: true
    environment:
#      - "constraint:dashboard==1"
      - "affinity:demo.dashboard==1"
  sensor:
    build:
      context: "./envirophat_sensor/"
    networks:
      - frontend
    privileged: true
    environment:
      - "affinity:container!=datacentersensor_sensor_*"
      - "constraint:sensor==1"
  redis:
    image: alexellis2/redis-arm:v6
    ports:
      - 6379/TCP
    networks:
      - frontend

networks:
  frontend:
    driver: overlay
