version: "2.0"
services:
  print:
    build ./redis_display/
    networks:
      - frontend

  redis:
    image: alexellis2/redis-arm:v6
    networks:
      - frontend
#      - default

networks:
  frontend:
    driver: overlay
