version: "2.0"
services:

  redis:
    image: alexellis2/redis-arm:v6
    ports:
      - 6379/TCP
    networks:
      - frontend

  unicorndashboard:
    build:
      context: "./multi_dashboard/"
    networks:
      - frontend
    privileged: true
    environment:
      - "constraint:demo.dashboard==1"
    depends_on:
      - redis

  sensor:
    build:
      context: "./envirophat_sensor/"
    networks:
      - frontend
    privileged: true
    environment:
      - "affinity:container!=datacentersensor_sensor_*"
      - "constraint:sensor==1"
    depends_on:
      - redis

networks:
  frontend:
    driver: overlay
