version: "2.0"
services:
  sensor:
    build:
      context: "./envirophat_sensor/"
    networks:
      - frontend
    privileged: true
    environment:
      - "affinity:container!=datacenter_sensor_sensor_*"
      - "affinity:sensor=1"
  dashboard:
    build:
      context: "./multi_dashboard/"
    networks:
      - frontend
    privileged: true
    environment:
      - "affinity:dashboard=1"
  redis:
    image: alexellis2/redis-arm:v6
    ports:
      - 6379/TCP
    networks:
      - frontend

networks:
  frontend:
    driver: overlay
