version: "2.0"
services:

  redis:
    image: alexellis2/redis-arm:v6
    ports:
      - 6379/TCP
    networks:
      - frontend
    environment:
      - "constraint:demo.web==1"

  web:
    build:
      context: "./webdashboard/"
    networks:
      - frontend
    privileged: true
    environment:
      - "constraint:demo.web==1"
      - QUIET=True
    ports:
      - "5001:5000"
    depends_on:
      - redis

  unicorn:
    build:
      context: "./multi_dashboard/"
    networks:
      - frontend
    privileged: true
    environment:
      - "constraint:demo.dashboard==1"
      - QUIET=True
      - TEMP_THRESHOLD=0.8
    depends_on:
      - redis

  sensor:
    build:
      context: "./envirophat_sensor/"
    networks:
      - frontend
    privileged: true
    environment:
      - "affinity:container!=datacentersensor_sensor_*"
      - "constraint:sensor==1"
      - TEMP_THRESHOLD=0.8
      - QUIET=True
    depends_on:
      - redis

networks:
  frontend:
    driver: overlay
